# Generated by Django 5.0.2 on 2024-09-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
    ]
