# Generated by Django 5.0.2 on 2024-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0002_tbl_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='categoria',
            field=models.CharField(default='sin comentarios', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='presentacion',
            field=models.CharField(default='sin comentarios', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='registro_sanitario',
            field=models.CharField(default='sin comentarios', max_length=100),
            preserve_default=False,
        ),
    ]
