# Generated by Django 5.0.2 on 2024-09-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0003_tbl_producto_categoria_tbl_producto_presentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_producto',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='tbl_producto',
            name='registro_sanitario',
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='imagen_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apishop.tbl_categoria'),
        ),
        migrations.CreateModel(
            name='tbl_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apishop.tbl_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_producto_por_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apishop.tbl_pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apishop.tbl_producto')),
            ],
        ),
    ]
