# Generated by Django 5.0.2 on 2024-09-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0004_tbl_categoria_tbl_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_categoria',
            name='descripcion',
        ),
    ]
