# Generated by Django 5.0.2 on 2024-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0005_remove_tbl_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='numero_de_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
