# Generated by Django 5.0.2 on 2024-09-15 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0006_tbl_producto_calificacion_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
    ]
