# Generated by Django 5.0.2 on 2024-09-15 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0007_alter_tbl_producto_calificacion_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='en_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
