# Generated by Django 5.0.2 on 2024-09-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0008_tbl_producto_en_oferta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
