# Generated by Django 5.0.2 on 2024-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0011_alter_tbl_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
