# Generated by Django 5.0.2 on 2024-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0012_alter_tbl_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='precio',
            field=models.IntegerField(default=1000),
        ),
    ]
