# Generated by Django 5.0.2 on 2024-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0013_tbl_producto_estado_alter_tbl_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
